name: "CursedKits"
main: "com.github.fabiogvdneto.kits.KitPlugin"
version: "0.1"
commands:
  kit:
    description: "Claim a kit."
  kits:
    description: "List all kits available for the player."
  createkit:
    description: "Create a kit."
  deletekit:
    description: "Delete a kit."
permissions:
  kits.command.kit:
    default: true
  kits.command.kits:
    default: true
  kits.command.createkit:
    default: op
  kits.command.deletekit:
    default: op
  kits.kit.*:
    default: op
  kits.basics:
    description: "Grants basic permissions for everyone."
    default: not op
    children:
      kits.command.kit: true
      kits.command.kits: true
  kits.admin:
    description: "Grants admin permissions."
    default: op
    children:
      kits.basics: true
      kits.command.createkit: true
      kits.command.deletekit: true
      kits.kit.*: true